idf_component_register(
    SRCS 
        "main.c"
        "application.c"
    INCLUDE_DIRS 
        "."
    REQUIRES 
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        driver
        freertos
        esp_timer
        esp_system
        esp_http_client
        esp_https_ota
        json
        linx_sdk
        linx_board_esp32
)